#!/usr/bin/env python3
"""Generate a lightweight markdown index of applications/ into Obsidian.

Not a backup of the full application packages (CVs, cover letters,
stretch logs stay only in this repo's gitignored applications/) --
just enough to answer "where have we already applied?" at a glance:
date, platform, company, title, status, url. Works across both legacy
and schema v2 records (both carry these fields).

Usage:
    scripts/export-applications-tracker.py
"""
from __future__ import annotations

import json
import os
import sys
from pathlib import Path


def load_dotenv_var(name: str) -> str | None:
    """Minimal .env reader -- no python-dotenv dependency for one script."""
    if name in os.environ:
        return os.environ[name]
    env_path = Path(".env")
    if not env_path.is_file():
        return None
    for line in env_path.read_text().splitlines():
        line = line.strip()
        if line.startswith(f"{name}="):
            return line.split("=", 1)[1].strip()
    return None


def tracker_path() -> Path:
    vault = load_dotenv_var("PRIVATE_BACKUP_VAULT_PATH")
    if not vault:
        sys.exit(
            "Error: PRIVATE_BACKUP_VAULT_PATH is not set in .env -- "
            "see .env.example. This is a personal path, never hardcoded "
            "or committed."
        )
    return Path(vault) / "applications-tracker.md"


def load_records() -> list[dict]:
    records = []
    for path in sorted(Path("applications").glob("*/record.json")):
        try:
            records.append(json.loads(path.read_text()))
        except (OSError, json.JSONDecodeError):
            continue
    return records


def render(records: list[dict]) -> str:
    records = sorted(records, key=lambda r: r.get("id", ""))
    v2_count = sum(1 for r in records if r.get("schema_version") == 2)

    lines = [
        "---",
        "title: Applications tracker",
        "type: note",
        "project: job-search-agent",
        "updated: 2026-09-24",
        "---",
        "",
        "# Applications tracker",
        "",
        f"Auto-generated by `scripts/export-applications-tracker.py` -- "
        f"do not hand-edit, regenerate instead. {len(records)} applications "
        f"({v2_count} on schema v2, {len(records) - v2_count} legacy). "
        f"Full packages (CV, cover letter, stretch log) stay in the repo's "
        f"gitignored `applications/`, not here.",
        "",
        "| Date | Platform | Company | Title | Status | Link |",
        "|---|---|---|---|---|---|",
    ]

    for r in records:
        date = r.get("id", "")[:10]
        platform = r.get("platform", "")
        company = (r.get("company", "") or "").replace("|", "\\|")
        title = (r.get("title", "") or "").replace("|", "\\|")
        status = r.get("status", "")
        url = r.get("url", "")
        link = f"[link]({url})" if url else ""
        lines.append(f"| {date} | {platform} | {company} | {title} | {status} | {link} |")

    return "\n".join(lines) + "\n"


def main() -> None:
    records = load_records()
    path = tracker_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render(records))
    print(f"Wrote {path} ({len(records)} applications)")


if __name__ == "__main__":
    main()
